#!/usr/bin/php
<?php
#thumbify: thumbnail generator
#(C) Copyright 2010 Nicholas Paun. All Rights Reserved.

$dest = $argv[1];
$imgsize ="190X163";
$images = glob("*.jpg");

foreach ($images as $photo)
 {
  echo ($photo."\n");
  passthru("convert -resize $imgsize '$photo' '$dest/thumb_$photo'");
 }
?>
