#!/bin/bash
#MintPhoto installer
#(C) Copyright 2009-2010 Nicholas Paun. All Rights Reserved.

INSTALLDIR="/srv/www/htdocs/mint4c/" #Directory to copy MintPhoto files
TOOLDIR="/usr/local/bin/" #Directory to copy tools

which php &> /dev/null
if [[ $? != 0 ]]; then
 echo "PHP not found"
 exit 1
fi

which jhead &> /dev/null
if [[ $? != 0 ]]; then
 echo "jhead not found"
fi

rsync -av ./ $INSTALLDIR
rsync -av ./tools/ $TOOLDIR

exit 0
